name: sillytavern_card_generator
description: "SillyTavern角色卡生成器 - 生成适用于SillyTavern平台的JSON格式角色卡"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.2.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.3
  http: ^1.1.0
  shared_preferences: ^2.2.2
  json_annotation: ^4.8.1
  equatable: ^2.0.5
  dartz: ^0.10.1
  connectivity_plus: ^5.0.2
  url_launcher: ^6.2.2
  path_provider: ^2.1.1
  flutter_quill: ^9.0.0
  uuid: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
